# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.2
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.2
      addons:
        apt:
          packages:
            - qt5-default
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/notZaki/CancerImagingArchive.jl.git"));
          Pkg.add(PackageSpec(url="https://github.com/notZaki/Perfusion.jl.git"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
