name = "RRIFT"
uuid = "24182d0a-53cc-4645-a8a8-b61be1753720"
authors = ["Zaki A"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
